Repository rapyuta-robotics/rapyuta-io-cli, pull requests merged in 2023-07, with the labels that each got.

#187 ✨ feat(project): adds yaspin implementation to project commands
  riocli/project/create.py
  riocli/project/delete.py
  riocli/project/features/__init__.py
  riocli/project/features/vpn.py
  riocli/project/inspect.py
  riocli/project/list.py
  riocli/project/model.py
  riocli/project/select.py
  riocli/project/util.py
Labels: enhancement, awaiting-approval, ready-to-merge

#188 ✨ feat(vpn): adds spinner and refactors implementation
  riocli/vpn/connect.py
  riocli/vpn/disconnect.py
  riocli/vpn/ping.py
  riocli/vpn/status.py
  riocli/vpn/util.py
Labels: enhancement, awaiting-review

#200 🔧 chore: bumps SDK version to v1.11.0
  Pipfile
  Pipfile.lock
  setup.py
Labels: chore

#184 ✨ feat(usergroup): adds usergroup command
  docs/source/index.rst
  docs/source/usergroup.rst
  riocli/apply/manifests/usergroup.yaml
  riocli/apply/resolver.py
  riocli/bootstrap.py
  riocli/jsonschema/schemas/usergroup-schema.yaml
  riocli/organization/utils.py
  riocli/usergroup/__init__.py
  riocli/usergroup/delete.py
  riocli/usergroup/inspect.py
  riocli/usergroup/list.py
  riocli/usergroup/model.py
  riocli/usergroup/util.py
Labels: feature, awaiting-review

#190 ✨ feat(deployment): adds command for updating deployment
  riocli/deployment/__init__.py
  riocli/deployment/update.py
Labels: feature, needs-work

#202 ✨ feat(organization): adds command to list users
  riocli/organization/__init__.py
  riocli/organization/users.py
  riocli/organization/utils.py
Labels: awaiting-approval, feature, awaiting-review

#174 ✨ feat: adds command to update the CLI
  Pipfile
  Pipfile.lock
  riocli/bootstrap.py
  riocli/utils/__init__.py
  setup.py
Labels: awaiting-approval, ready-to-merge, feature

#178 ✨ feat(deployment): adds flags for retry count and sleep interval
  riocli/apply/__init__.py
  riocli/build/model.py
  riocli/deployment/model.py
  riocli/device/model.py
  riocli/disk/model.py
  riocli/managedservice/model.py
  riocli/model/base.py
  riocli/network/model.py
  riocli/package/model.py
  riocli/project/model.py
  riocli/secret/model.py
  riocli/static_route/model.py
Labels: enhancement, needs-work

#198 🚀 perf(deployment): polls deployment till provisioning phase
  riocli/deployment/model.py
  riocli/deployment/util.py
Labels: ready-to-merge

#138 ✨ feat(static-route): updates spinner and other implementations
  riocli/static_route/__init__.py
  riocli/static_route/create.py
  riocli/static_route/delete.py
  riocli/static_route/inspect.py
  riocli/static_route/list.py
  riocli/static_route/model.py
  riocli/static_route/open.py
  riocli/static_route/util.py
Labels: enhancement, awaiting-review

#189 ✨ feat(auth): updates spinner and refactors existing code
  riocli/auth/__init__.py
  riocli/auth/login.py
  riocli/auth/logout.py
  riocli/auth/refresh_token.py
  riocli/auth/staging.py
  riocli/auth/status.py
  riocli/auth/token.py
  riocli/auth/util.py
Labels: enhancement, awaiting-review

#197 ✨ feat(network): updates spinner and refactors existing commands
  riocli/network/__init__.py
  riocli/network/create.py
  riocli/network/delete.py
  riocli/network/inspect.py
  riocli/network/list.py
  riocli/network/model.py
  riocli/network/native_network.py
  riocli/network/routed_network.py
  riocli/network/util.py
Labels: enhancement, awaiting-review

#196 ✨ feat(chart): adds spinner and refactors code
  riocli/chart/__init__.py
  riocli/chart/apply.py
  riocli/chart/chart.py
  riocli/chart/delete.py
  riocli/chart/info.py
  riocli/chart/list.py
  riocli/chart/search.py
Labels: enhancement, awaiting-review

#194 ✨ feat(deployment): updates spinner and refactors existing code
  riocli/deployment/__init__.py
  riocli/deployment/delete.py
  riocli/deployment/execute.py
  riocli/deployment/inspect.py
  riocli/deployment/list.py
  riocli/deployment/logs.py
  riocli/deployment/model.py
  riocli/deployment/run.py
  riocli/deployment/status.py
  riocli/deployment/wait.py
Labels: enhancement, awaiting-review

#193 ✨ feat(device): adds yaspin spinnner to device commands
  riocli/device/config.py
  riocli/device/delete.py
  riocli/device/deployment.py
  riocli/device/execute.py
  riocli/device/files.py
  riocli/device/model.py
  riocli/device/tools/device_init.py
  riocli/device/tools/ssh.py
  riocli/device/tools/util.py
  riocli/device/vpn.py
  riocli/utils/__init__.py
Labels: enhancement, awaiting-review

#195 ✨ feat(disk): updates spinner and existing implementation
  riocli/disk/__init__.py
  riocli/disk/create.py
  riocli/disk/delete.py
  riocli/disk/list.py
  riocli/disk/model.py
  riocli/disk/util.py
Labels: enhancement, awaiting-review

#192 ✨ feat(apply): adds yaspin spinner to apply family of commands
  riocli/apply/__init__.py
  riocli/apply/explain.py
  riocli/apply/parse.py
  riocli/apply/template.py
  riocli/model/base.py
Labels: enhancement, awaiting-review

#206 🔨 refactor(constants): updates the symbols to emojis
  riocli/constants/symbols.py
Labels: enhancement

#205 🐛 fix(jsonschema): adds regex pattern to usergroup schema
  riocli/jsonschema/schemas/usergroup-schema.yaml
Labels: bug
