Repository rapyuta-robotics/rapyuta-io-cli, pull requests merged in 2024-01, with the labels that each got.

#253 chore: pins yaspin version to v2.5.0
  Pipfile
  Pipfile.lock
  setup.py
Labels: 🔧 chore

#241 🔨 refactor!: removes build from the CLI
  docs/source/build.rst
  docs/source/index.rst
  riocli/apply/manifests/build.yaml
  riocli/apply/manifests/package-nonros-cloud.yaml
  riocli/apply/manifests/package-nonros-device.yaml
  riocli/apply/manifests/package-ros-cloud.yaml
  riocli/apply/manifests/package-ros-device-no-rosbag.yaml
  riocli/apply/manifests/package-ros-device-rosbag.yaml
  riocli/apply/manifests/package.yaml
  riocli/apply/parse.py
  riocli/apply/resolver.py
  riocli/bootstrap.py
  riocli/build/__init__.py
  riocli/build/create.py
  riocli/build/delete.py
  riocli/build/import_build.py
  riocli/build/inspect.py
  riocli/build/list.py
  riocli/build/logs.py
  riocli/build/model.py
  riocli/build/trigger.py
  riocli/build/util.py
  riocli/deployment/update.py
  riocli/jsonschema/schemas/build-schema.yaml
  riocli/jsonschema/schemas/deployment-schema.yaml
  riocli/jsonschema/schemas/package-schema.yaml
  riocli/jsonschema/schemas/primitives.yaml
  riocli/package/inspect.py
  riocli/package/model.py
Labels: 🔨 refactor

#260 fix(disk): implements retry mechanism for disk deletion
  riocli/disk/model.py
Labels: 🐛 bug

#262 fix: updates default service urls in api calls
  riocli/apply/resolver.py
  riocli/deployment/logs.py
  riocli/disk/util.py
  riocli/organization/utils.py
  riocli/parameter/utils.py
  riocli/utils/execute.py
Labels: 🐛 bug
