Repository rapyuta-robotics/rapyuta-io-cli, pull requests merged in 2024-05, with the labels that each got.

#301 fix(secret): corrects the corresponding find functor
  riocli/apply/resolver.py
  riocli/secret/model.py
Labels: 🐛 bug

#303 feat(vpn): add support for registering machine for Android or iOS
  riocli/v2client/client.py
  riocli/vpn/__init__.py
  riocli/vpn/connect.py
  riocli/vpn/machines.py
  riocli/vpn/util.py
Labels: ✨ feature

#302 :tada: release: v7.4.0
  Pipfile
  Pipfile.lock
  docs/source/conf.py
  docs/source/config_tree.rst
  docs/source/index.rst
  riocli/apply/parse.py
  riocli/apply/resolver.py
  riocli/bootstrap.py
  riocli/config/__init__.py
  riocli/config/config.py
  riocli/configtree/__init__.py
  riocli/configtree/etcd.py
  riocli/configtree/import_keys.py
  riocli/configtree/revision.py
  riocli/configtree/tree.py
  riocli/configtree/util.py
  riocli/exceptions/__init__.py
  riocli/secret/model.py
  riocli/utils/graph.py
  riocli/utils/mermaid.py
  riocli/utils/state.py
  riocli/v2client/client.py
  riocli/vpn/__init__.py
  riocli/vpn/connect.py
  riocli/vpn/machines.py
  riocli/vpn/util.py
  setup.py
Labels: 🐛 bug, ✨ feature

#305 fix(vpn): fix the expiry time formatting for vpn binding
  riocli/vpn/util.py
Labels: 🐛 bug

#309 chore: updates python_requires in setup.py
  setup.py
Labels: 🔧 chore
