Repository rapyuta-robotics/rapyuta-io-cli, pull requests merged in 2024-07, with the labels that each got.

#327 refactor(hwil): removes ssh shell via paramiko
  Pipfile
  Pipfile.lock
  riocli/hwil/ssh.py
  riocli/utils/ssh_shell.py
  setup.py
Labels: 🔨 refactor

#326 ✨ feat: implements update and delete for virtual devices
  riocli/device/model.py
  riocli/device/util.py
  riocli/hwil/util.py
  riocli/hwilclient/client.py
Labels: ✨ feature

#328 fix(device): sets highperf label on virtual device
  riocli/device/util.py
Labels: 🐛 bug

#324 fix(project): updates subnet when vpn is already enabled
  riocli/project/features/vpn.py
Labels: 🐛 bug

#330 fix(v2client): set organizationguid header by default
  riocli/v2client/client.py
Labels: 🐛 bug

#332 feat(template): sort rendered template by file name
  riocli/apply/util.py
Labels: ✨ feature

#338 fix(jsonschema): add platform as a product for virtual devices
  riocli/apply/manifests/device.yaml
  riocli/jsonschema/schemas/device-schema.yaml
Labels: 🐛 bug

#336 fix(configtree): prefix keys with '/' when importing to etcd
  riocli/configtree/etcd.py
Labels: 🐛 bug

#337 fix(configtree): update sentinel key when tree is imported in etcd
  riocli/configtree/etcd.py
Labels: 🐛 bug

#339 fix(organization): fix organization select command
  riocli/organization/select.py
Labels: 🐛 bug
