Repository rapyuta-robotics/rapyuta-io-cli, pull requests merged in 2024-11, with the labels that each got.

#379 feat(apply): adds template func to get interface ip
  pyproject.toml
  riocli/apply/filters.py
  uv.lock
Labels: ✨ feature

#383 fix(organization): fixes key error when no org is selected
  riocli/organization/list.py
Labels: 🐛 bug

#386 🎉 release: 9.2.0
  .github/workflows/upload-appimage.yml
  pyproject.toml
  riocli/apply/filters.py
  riocli/device/report.py
  riocli/organization/list.py
  uv.lock
Labels: :tada: release

#387 feat: adds option for virtual device expiry
  riocli/apply/manifests/device.yaml
  riocli/device/util.py
  riocli/hwil/create.py
  riocli/jsonschema/schemas/device-schema.yaml
Labels: ✨ feature

#365 feat: add option to exec commands asynchronously
  pyproject.toml
  riocli/deployment/execute.py
  riocli/device/execute.py
  riocli/utils/execute.py
  uv.lock
Labels: ✨ feature

#391 feat: add RIO_CONFIG env override
  riocli/config/config.py
Labels: ✨ feature

#392 chore: syncs devel with main
  CHANGELOG.md
  riocli/bootstrap.py
  riocli/config/config.py
Labels: 🔧 chore
