Repository rapyuta-robotics/rapyuta-io-cli, pull requests merged in 2024-09, with the labels that each got.

#349 fix(deployment): inspect deployment with guid
  riocli/deployment/inspect.py
Labels: 🐛 bug

#353 chore: bumps rapyuta_io and jsonschema versions
  Pipfile
  Pipfile.lock
  setup.py
Labels: 🔧 chore

#354 feat(scripts): adds install script for appimages
  .github/workflows/gh-pages.yml
  scripts/install.sh
Labels: ✨ feature

#355 🔧 chore: adds rapyuta.io trademark banner
  scripts/install.sh
Labels: 🔧 chore
